### ISSUE TITLE
Setup Project Repo

### ISSUE THREAD

**Issue by vidban** [chingu-voyages/v23-chimeras-team-03#2]
**Task Description**
Setup the project repo based on the technical stack chosen by the team.

- [ ] Create folder structure
- [ ] Setup package.json with known dependencies
- [ ]  Create fixed branches based on the Git Workflow decided on by the team
- [ ]  Create an initial readme.md. 

**Technical Considerations**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
