### ISSUE TITLE
[EPIC} Search for recipes by default

### ISSUE THREAD

**Issue by vidban** [chingu-voyages/v23-chimeras-team-03#6]
**Epic Description**

__Ability to search for recipes pulled from the internet by default (before registration)

**** Value Addition to Product**

**Definition of Done**

**User Stories**

1. As a User, I shall be able to view recipes on the app’s landing page without login in

**Tasks**

- [ ] Create Landing Page

- [ ] Research and add food recipe API

- [ ] Code a functional component using Array Map to display food recipes from API
